// Stride arithmetic for the view explorer, in the same rules torch uses:
// a view rewrites shape, stride, and offset over an untouched storage, and
// contiguity is whether the strides equal the row-major ones for the shape.
// The instrument is only honest if this matches the real library, so
// strides.test.ts checks every step against the corpus generated by running
// the equivalent chains on torch 2.2.2.

export interface View {
  shape: number[]
  stride: number[]
  offset: number
}

export type Op =
  | { kind: 't' }
  | { kind: 'transpose'; a: number; b: number }
  | { kind: 'permute'; order: number[] }
  | { kind: 'unsqueeze'; dim: number }
  | { kind: 'sliceRows'; start: number }
  | { kind: 'strideCols'; step: number }
  | { kind: 'flatten' }
  | { kind: 'contiguous' }

export const rowMajorStrides = (shape: number[]): number[] => {
  const out = new Array<number>(shape.length)
  let acc = 1
  for (let i = shape.length - 1; i >= 0; i--) {
    out[i] = acc
    acc *= shape[i]!
  }
  return out
}

export const isContiguous = (v: View): boolean => {
  // torch treats a tensor with any zero-size dimension as contiguous, and
  // size-1 dimensions carry no constraint because they are never stepped.
  if (v.shape.some((d) => d === 0)) return true
  const want = rowMajorStrides(v.shape)
  return v.shape.every((d, i) => d === 1 || v.stride[i] === want[i])
}

export const baseView = (shape: number[]): View => ({
  shape: [...shape],
  stride: rowMajorStrides(shape),
  offset: 0,
})

const swap = <T,>(xs: T[], a: number, b: number): T[] => {
  const out = [...xs]
  const t = out[a]!
  out[a] = out[b]!
  out[b] = t
  return out
}

/** Apply one op, returning the new view. Throws when torch would refuse. */
export function apply(v: View, op: Op): View {
  switch (op.kind) {
    case 't': {
      if (v.shape.length !== 2) throw new Error('t() wants a 2D tensor')
      return { shape: swap(v.shape, 0, 1), stride: swap(v.stride, 0, 1), offset: v.offset }
    }
    case 'transpose': {
      if (op.a >= v.shape.length || op.b >= v.shape.length) throw new Error('axis out of range')
      return { shape: swap(v.shape, op.a, op.b), stride: swap(v.stride, op.a, op.b), offset: v.offset }
    }
    case 'permute': {
      if (op.order.length !== v.shape.length) throw new Error('permute wants every axis')
      return {
        shape: op.order.map((i) => v.shape[i]!),
        stride: op.order.map((i) => v.stride[i]!),
        offset: v.offset,
      }
    }
    case 'unsqueeze': {
      const shape = [...v.shape]
      const stride = [...v.stride]
      // the inserted axis has size 1, so its stride never gets stepped;
      // torch fills it with the size of what follows, which is what a
      // row-major expansion of the remaining dims would use.
      const fill = op.dim < v.stride.length ? v.stride[op.dim]! * v.shape[op.dim]! : 1
      shape.splice(op.dim, 0, 1)
      stride.splice(op.dim, 0, fill)
      return { shape, stride, offset: v.offset }
    }
    case 'sliceRows': {
      // x[start:] keeps every stride and moves the window forward
      const shape = [...v.shape]
      shape[0] = Math.max(0, shape[0]! - op.start)
      return { shape, stride: [...v.stride], offset: v.offset + op.start * v.stride[0]! }
    }
    case 'strideCols': {
      // x[:, ::step] multiplies the stepped axis's stride
      if (v.shape.length < 2) throw new Error('needs a second axis')
      const shape = [...v.shape]
      const stride = [...v.stride]
      shape[1] = Math.ceil(shape[1]! / op.step)
      stride[1] = stride[1]! * op.step
      return { shape, stride, offset: v.offset }
    }
    case 'flatten': {
      // a flatten of a non-contiguous view copies, so the result is a fresh
      // contiguous 1D tensor either way
      const n = v.shape.reduce((a, b) => a * b, 1)
      return { shape: [n], stride: [1], offset: isContiguous(v) ? v.offset : 0 }
    }
    case 'contiguous': {
      if (isContiguous(v)) return v
      return { shape: [...v.shape], stride: rowMajorStrides(v.shape), offset: 0 }
    }
  }
}

export const applyAll = (shape: number[], ops: Op[]): View => ops.reduce(apply, baseView(shape))

export const fmt = (xs: number[]) => `(${xs.join(', ')})`
